kind: pipeline
type: docker
name: branch

steps:
  - name: buildLocal
    image: debian:buster-slim
    commands:
      - mvn clean package

trigger:
  branch:
    - feature/*

---
kind: pipeline
type: docker
name: pullrequest

steps:
  - name: buildLocal
    image: debian:buster-slim
    commands:
      - mvn clean package

trigger:
  event:
    - pull_request

---
kind: pipeline
type: docker
name: buildPush

steps:
  - name: buildPush
    image: maven:3-jdk-11
    commands:
      - mvn clean package

trigger:
  branch:
    - master
  event:
    exclude:
      - pull_request