kind: pipeline
type: docker
name: branch

steps:
  - name: getTimestamp
    image: debian:buster-slim
    commands:
      - echo -n "$(date +%Y-%m-%d-%H%M).${DRONE_COMMIT_SHA:0:7},latest" > .tags

  - name: dockerBuild
    image: plugins/docker
    settings:
      repo: kghf/openjdk11
      dry_run: true
      build_args:
        - SIMPLE_DASH_DL_URL=https://github.com/kutyla-philipp/simple-dash/archive/master.zip

trigger:
  branch:
    - feature/*

---
kind: pipeline
type: docker
name: buildPush

steps:
  - name: dockerBuildPushJRE
    image: plugins/docker
    settings:
      repo: kghf/openjdk11-jre
      dockerfile: jre/Dockerfile
      username: larskghf
      password:
        from_secret: docker_password
      build_args:
        JAVAVERSION: ${DRONE_TAG}
        DOWNLOADURL: https://github.com/AdoptOpenJDK/openjdk11-binaries/releases/download/jdk-11.0.6%2B10/OpenJDK11U-jre_x64_linux_hotspot_11.0.6_10.tar.gz
      tags:
        - ${DRONE_TAG}.${DRONE_COMMIT_SHA:0:7}
        - latest
  - name: dockerBuildPushJDK
    image: plugins/docker
    settings:
      repo: kghf/openjdk11-jdk
      dockerfile: jdk/Dockerfile
      username: larskghf
      password:
        from_secret: docker_password
      build_args:
        JAVAVERSION: ${DRONE_TAG}
        DOWNLOADURL: https://github.com/AdoptOpenJDK/openjdk11-binaries/releases/download/jdk-11.0.6%2B10/OpenJDK11U-jdk_x64_linux_hotspot_11.0.6_10.tar.gz
      tags:
        - ${DRONE_TAG}.${DRONE_COMMIT_SHA:0:7}
        - latest
trigger:
  branch:
    - master
  event:
    - tag