kind: pipeline
type: docker
name: branch

environment:
  JAVAVERSION2: asdfasdf

steps:
  - name: getTimestamp
    image: debian:buster-slim
    environment:
      JAVAVERSION: 11.0.6-10
    commands:
      - echo $JAVAVERSION2
      - echo -n "$${JAVAVERSION}_${DRONE_COMMIT_SHA:0:8},latest" > .tags
      - cat .tags
#  - name: dockerBuildJDK
#    image: plugins/docker
#    environment:
#      JAVAVERSION: 11.0.6-10
#      DOWNLOADURL: https://github.com/AdoptOpenJDK/openjdk11-binaries/releases/download/jdk-11.0.6%2B10/OpenJDK11U-jdk_x64_linux_hotspot_11.0.6_10.tar.gz
#    settings:
#      repo: kghf/openjdk11-jdk
#      dockerfile: jdk/Dockerfile
#      dry_run: true
#      build_args_from_env:
#        - JAVAVERSION
#        - DOWNLOADURL

trigger:
  branch:
    - feature/*

---
kind: pipeline
type: docker
name: buildPushJDK

steps:
  - name: getTimestamp
    image: debian:buster-slim
    environment:
      JAVAVERSION: 11.0.6-10
    commands:
      - echo -n "$JAVAVERSION_${DRONE_COMMIT_SHA:0:8},latest" > .tags
  - name: dockerBuildPushJDK
    image: plugins/docker
    environment:
      JAVAVERSION: 11.0.6-10
      DOWNLOADURL: https://github.com/AdoptOpenJDK/openjdk11-binaries/releases/download/jdk-11.0.6%2B10/OpenJDK11U-jdk_x64_linux_hotspot_11.0.6_10.tar.gz
    settings:
      repo: kghf/openjdk11-jdk
      dockerfile: jdk/Dockerfile
      username: larskghf
      password:
        from_secret: docker_password
      build_args_from_env:
        - JAVAVERSION
        - DOWNLOADURL

trigger:
  branch:
    - master
  event:
    exclude:
      - pull_request
